### ISSUE TITLE
Mise à jour du second semestre 2020

### ISSUE THREAD

**Issue by YaNoo** [etalab/DVF-app#105]
Bonjour,

La mise à jour du second semestre 2020 a été mise à jour sur https://cadastre.data.gouv.fr/data/etalab-dvf/2021-04/csv/ pouvez-vous faire la mise à jour du site https://app.dvf.etalab.gouv.fr/ ?

Merci beaucoup.

**Comment by toopoormaghell** [comment]
Bonjour, je me posais la même question.

**Comment by coisnepe** [comment]
Bonjour @GllmR @marion-paclot @jdesboeufs , auriez-vous une idée de quand les nouveaux csv seront importés ? Merci !

**Comment by FredericGodest** [comment]
Hello ! J'utilise l'API mais elle ne semble pas être à jour (dernière année 2019) est ce normal ?

**Comment by ThomasG77** [comment]
Pour la MAJ, les fichiers CSV sont sur https://files.data.gouv.fr/geo-dvf/2021-06/csv/

@FredericGodest

> J'utilise l'API.

Vous parlez de http://api.cquest.org/dvf?

**Comment by FredericGodest** [comment]
Oui j'ai vu :) je vais regarder pour l'API mais je ne suis pas sûr

**Comment by ThomasG77** [comment]
Pour l'API http://api.cquest.org/dvf, il s'agissait d'un "one-shot" lors d'un hackathon. Il n'est pas utilisé ni géré par Etalab. La donnée date de 2019. Vous pouvez accéder au code source sur https://github.com/cquest/dvf_as_api
