### ISSUE TITLE
Guadeloupe et Martinique HS

### ISSUE THREAD

**Issue by barnabejo** [etalab/DVF-app#118]
bonjour
l'accés à etalab pour la guadeloupe te la martinique ne fonctionne plus, ni sur ios ni sous windows, bref plus d'accés

merci de corriger
cordialement
barnabejo

**Comment by ThomasG77** [comment]
Bonjour,

Résolu. Un effet de bord de la mise à jour des dernières données cadastre.
Merci de commenter et/ou réouvrir si le problème persiste.
