### ISSUE TITLE
quid des mutations sur plusieurs sections

### ISSUE THREAD

**Issue by manuamador** [etalab/DVF-app#25]
Bonjour,
Dans le découpage, il semblerait que les mutations sont cloisonnées par département, commune, section. Mais je crois qu'une mutation peut concerner plusieurs sections. est-ce bien pris en compte par l'outil ?

**Comment by marion-paclot** [comment]
Bonjour, 
Malheureusement non, car l'identifiant de mutation a été retiré au moment de la publication de la base. Or j'utilise les données en open data, les mêmes que celles du grand public. 
La solution que j'ai utilisée pour identifier les biens (bati ou terrain) d'une même mutation est la combinaison de prix, date et section. Donc effectivement, si deux terrains ne sont pas dans la même section, ils ne seront pas associé. D'après un expert de cette base, moins de 1% des mutations sont cross - communes / départements. Il y a donc peut être des erreurs, mais espérons qu'elles soient vraiment rares ; je n'ai pas réellement d'autre solution. Vous avez une idée pour corriger cette limite ?

**Comment by jdesboeufs** [comment]
Pour les [CSV retravaillés](https://github.com/etalab/dvf/blob/master/README-CSV.md) c'est la séquence des enregistrements qui est utilisée pour créer l'identifiant de mutation.
Un changement de date ou de valeur foncière incrémente le compteur.

**Comment by marion-paclot** [comment]
@jdesboeufs, je n'ai pas eu encore le temps de basculer sur tes fichiers. Mais effectivement, si on part du principe que c'est "trié", ton fichier sera encore plus précis que le mien.

**Comment by hawisizu** [comment]
Bonjour! 

de ce que je comprend de votre discussion, on peut avoir plusieurs mutations correspondant à la même vente, du genre: 

{  
   "numero_disposition":"000001",
   "date_mutation":"2018-02-28",
   "nature_mutation":"Vente",
   "valeur_fonciere":11919300,
   "numero_voie":"5",
   "suffixe_numero":"",
   "type_voie":"RUE",
   "code_voie":"1087",
   "voie":"BONAPARTE",
   "code_postal":"75006",
   "commune":"PARIS 06",
   "code_departement":"75",
   "code_commune":"75106",
   "prefixe_section":null,
   "section":"BM",
   "numero_plan":"75106000BM0052",
   "numero_volume":null,
   "lot_1":"51",
   "surface_lot_1":307.71,
   "lot_2":"52",
   "surface_lot_2":null,
   "lot_3":"53",
   "surface_lot_3":null,
   "lot_4":"54",
   "surface_lot_4":null,
   "lot_5":null,
   "surface_lot_51":null,
   "nombre_lots":"4",
   "code_type_local":"2",
   "type_local":"Appartement",
   "identifiant_local":null,
   "surface_relle_bati":290,
   "nombre_pieces_principales":6,
   "nature_culture":null,
   "nature_culture_speciale":null,
   "surface_terrain":null,
   "lat":48.856994,
   "lon":2.335396
},
{  
   "numero_disposition":"000001",
   "date_mutation":"2018-02-28",
   "nature_mutation":"Vente",
   "valeur_fonciere":11919300,
   "numero_voie":"5",
   "suffixe_numero":"",
   "type_voie":"RUE",
   "code_voie":"1087",
   "voie":"BONAPARTE",
   "code_postal":"75006",
   "commune":"PARIS 06",
   "code_departement":"75",
   "code_commune":"75106",
   "prefixe_section":null,
   "section":"BM",
   "numero_plan":"75106000BM0052",
   "numero_volume":null,
   "lot_1":"15",
   "surface_lot_1":49.06,
   "lot_2":"30",
   "surface_lot_2":null,
   "lot_3":null,
   "surface_lot_3":null,
   "lot_4":null,
   "surface_lot_4":null,
   "lot_5":null,
   "surface_lot_51":null,
   "nombre_lots":"2",
   "code_type_local":"2",
   "type_local":"Appartement",
   "identifiant_local":null,
   "surface_relle_bati":48,
   "nombre_pieces_principales":2,
   "nature_culture":null,
   "nature_culture_speciale":null,
   "surface_terrain":null,
   "lat":48.856994,
   "lon":2.335396
},
{  
   "numero_disposition":"000001",
   "date_mutation":"2018-02-28",
   "nature_mutation":"Vente",
   "valeur_fonciere":11919300,
   "numero_voie":"5",
   "suffixe_numero":"",
   "type_voie":"RUE",
   "code_voie":"1087",
   "voie":"BONAPARTE",
   "code_postal":"75006",
   "commune":"PARIS 06",
   "code_departement":"75",
   "code_commune":"75106",
   "prefixe_section":null,
   "section":"BM",
   "numero_plan":"75106000BM0052",
   "numero_volume":null,
   "lot_1":"22",
   "surface_lot_1":null,
   "lot_2":null,
   "surface_lot_2":null,
   "lot_3":null,
   "surface_lot_3":null,
   "lot_4":null,
   "surface_lot_4":null,
   "lot_5":null,
   "surface_lot_51":null,
   "nombre_lots":"1",
   "code_type_local":"2",
   "type_local":"Appartement",
   "identifiant_local":null,
   "surface_relle_bati":6,
   "nombre_pieces_principales":1,
   "nature_culture":null,
   "nature_culture_speciale":null,
   "surface_terrain":null,
   "lat":48.856994,
   "lon":2.335396
}

@marion-paclot de ce que vous expliquez, on peut grouper par date + prix + code postal + section c'est bien ca? Je cherche à avoir le prix/m2 de chaque vente. 

Je vais essayer de voir si je vois des ventes cross sections sur Paris, je reviens vers vous... 

Merci!

**Comment by marion-paclot** [comment]
J'ai utilisé la base retravaillée par @jdesboeufs, qui a crée un id de mutation plus intelligent que le mien : il part du principe que le fichier est trié, et l'id s'incrémente lorsque la date ou le prix changent. 
Normalement, c'est beaucoup plus malin. Néanmoins, je n'affiche pas (à vérifier) encore sur la carte lorsqu'un bout de terrain est acheté dans une autre section.

**Comment by hawisizu** [comment]
Merci pour la réponse, je vais aussi passer sur ces fichiers du coup!
