### ISSUE TITLE
Ajouter le prix au m²

### ISSUE THREAD

**Issue by reda-alaoui** [etalab/DVF-app#53]

**Comment by manuamador** [comment]
Ce n’est pas trop compliqué à calculer. Nous le faisons en séparant le bâti du non bâti. Si la mutation contient du bâti on considère La mutation comme du bâti et on somme les surfaces bâties.
Si il n’y a que du non bâti, on somme les terrains...

**Comment by marion-paclot** [comment]
Bonsoir à tous les deux. Ce n'est pas prévu, bien que pas compliqué, car la réalité est que le prix n'est pas un prix au mètre carré. Par exemple, certaines transactions ne couvrent qu'un % du bien (exemple : je vends à mon conjoint 50% de mon appartement : le prix sera le montant réel de la transaction alors que le métrage sera 100% de l'appartement). Nous n'affichons strictement que des données présentes dans la base, sans aucun calcul ou retraitement de valeur.
