### ISSUE TITLE
Vendée - Les Sables-d'Olonne - Erreur 400

### ISSUE THREAD

**Issue by fm89** [etalab/DVF-app#55]
Quand on choisit **85 - Vendée**, puis **Les Sables-d'Olonne**, rien ne se passe. La console affiche

![image](https://user-images.githubusercontent.com/47399735/57483334-e5f9c600-72a6-11e9-8c19-af41fe6cae96.png)

**Comment by jdesboeufs** [comment]
C'est corrigé !
Merci pour le signalement.
