### ISSUE TITLE
Pas d'affichage informations

### ISSUE THREAD

**Issue by rVs21** [etalab/DVF-app#59]
Bonjour,

Merci pour le travail réalisé.

Il doit y avoir des problèmes liés aux nouvelles communes : 
Par exemple 89 Montholon 473ZN

Pas d'affichage de l'information concernant la vente si clic sur une parcelle bleue.

Cordialement.

**Comment by marion-paclot** [comment]
Merci de nous avoir signalé cela 
@jdesboeufs @tmerlier le travail sur les communes nouvelles a sauté lors de la PR désastreuse... Je dirais que ça rentre dans les priorités :D

**Comment by jdesboeufs** [comment]
Je regarde.

**Comment by jdesboeufs** [comment]
Alors cette fois ce n'est pas du travail qui a sauté, mais un effet de bord lié au passage à Mapbox GL.
En gros quand on clique sur ces parcelles, on "quitte" la section + on entre dans la parcelle, donc on a plus de données.
