### ISSUE TITLE
Couleur des parcelles avec transaction

### ISSUE THREAD

**Issue by fm89** [etalab/DVF-app#62]
Sur certains terrains, c'est particulièrement dur de reconnaître le bleu du "il y a une transaction ici". Par exemple

![image](https://user-images.githubusercontent.com/47399735/57583569-e9bd6080-74d1-11e9-854f-743f6a375f0b.png)

Est-ce qu'on pourrait avoir une couleur plus flash ?

**Comment by marion-paclot** [comment]
C'est fait. Merci
