### ISSUE TITLE
Failed to initialize WebGL

### ISSUE THREAD

**Issue by kriom** [etalab/DVF-app#69]
Pour information depuis le commit **replace-leaflet** 2720ba80cd9bb4d3347f80facacbd2790e1ce9f6 WebGL est obligatoire.

Cela implique que l'on perd une partie des utilisateurs ayant un matériel ne supportant pas cette fonctionnalité.

![Screenshot from 2019-05-17 09-21-29](https://user-images.githubusercontent.com/3259059/57910322-4f6c6c80-7885-11e9-9b12-54a7c899e2ff.png)

@tmerlier Est-ce envisageable d'avoir une rétrocompatibilité avec leaflet dans le cas ou WebGL ne fonctionnerait pas ?

Bien cordialement,

**Comment by jdesboeufs** [comment]
Bonjour @kriom.

Ce n'est pas prévu. La majorité des incompatibilités sont dues à des désactivations par les utilisateurs ou à des problèmes de drivers sous certaines versions de Linux.
Nous n'avons pas eu de signalements de la part de utilisateurs "normaux" depuis la bascule.

Désolé de ne pas vous considérer comme comme un utilisateur normal, vous savez faire des PR et ouvrir la console d'un navigateur :D

Si des plaintes venaient à se multiplier nous aviserions.

**Comment by jdesboeufs** [comment]
Et encore une fois merci pour le retour :)

**Comment by kriom** [comment]
Ok merci, ça me va.
L'objectif était surtout d'informer.
A+ :)
