### ISSUE TITLE
Site HS aujourdhui ?

### ISSUE THREAD

**Issue by FlorianHergo** [etalab/DVF-app#74]
Bonjour,

Semble ne pas fonctionne aujourd'hui la même chose chez vous ?
Toutes les inputs du menu ne sont pas accessible. Pas de carte au centre.

Chrome Version 76.0.3809.100 + Windows 10.

**Comment by marion-paclot** [comment]
Aucun problème à signaler de mon côté ni aujourd'hui ni hier. On ne modifie pas grand chose en ce moment, donc assez étrange. Si quelqu'un a une idée ou le même problème, qu'il réouvre une issue.
