### ISSUE TITLE
MISE A JOUR DES DONNÉES DVF

### ISSUE THREAD

**Issue by gillessimon** [etalab/DVF-app#76]
Bonjour, il était - me semble t'il - prévu une mise à jour des données DVF et cela 2 fois par an en Avril et Octobre, quelqu'un saurait-il quand la mise à jour d'Octobre aura lieu et comment nous serons prévenus que les nouvelles données immobilières ont été mises à jour?
Par avance merci,
Gilles.

**Comment by marion-paclot** [comment]
Bonjour, 
Comme vous l'avez très certainement compris, les données représentée dans cette application sont produites par la dgfip, alors que cette application est proposée par Etalab. Nous ne sommes donc pas en charge des mises à jour, dont nous dépendons tout autant que n'importe qui. Nous sommes encore en octobre, donc encore un peu de patience. Si une date plus précise était connue, elle aurait été communiquée. Pour savoir si les données ont été mises à jour, rendez-vous sur les pages dvf de data.gouv.fr, qui est l'unique source publique pour ces données. Il faudra ensuite compte un jour ou deux pour que nous les intégrions au site. _Mon ton sans doute un peu sec s'explique par le fait que j'en suis à la 45ème réponse à cette question (par mail, par les forums de data.gouv.fr)._

**Comment by gillessimon** [comment]
Réponse de la DGFIP ci-dessous:

Bonjour,

La mise à jour du jeu de données DVF aura lieu dans le courant de la dernière semaine d'octobre.

Cordialement,

Le Bureau CL2A
DGFIP - Service des collectivités locales

-------- Message original --------
Sujet : Fwd: [etalab/DVF-app] MISE A JOUR DES DONNÉES DVF (#76)
De : Gilles Simon <gillessimon00@gmail.com>
Pour : Cl2a Fdl (Pla) <bureau.cl2a-fdl@dgfip.finances.gouv.fr>

Date : Samedi 19 Octobre 2019, 11:19

Bonjour,
puis-je me permettre de vous demander la date à laquelle la mise à jour d’Octobre 2019 va être publiée ?
Merci par avance,

Cordialement,

Gilles Simon
