### ISSUE TITLE
Mise a jour de octobre 2020 ?

### ISSUE THREAD

**Issue by FlorianHergo** [etalab/DVF-app#93]
Bonjour,

La MAJ est sortie le : _Publiée le 26 octobre 2020 17:23_
Savez-vous dans combien de temps elle sera disponible sur app.dvf.etalab.gouv.fr ?

En vous remerciant,
Cordialement.

**Comment by benfonty** [comment]
Les données de 2020 n'ont pas l'air de se trouver [à l'endroit où ils vont les chercher](https://cadastre.data.gouv.fr/data/etalab-dvf).

On peut trouver les données [ici](https://www.data.gouv.fr/fr/datasets/5c4ae55a634f4117716d5656/) mais elles ne sont pas présentées exactement pareil.

Je ne sais pas si ils attendent que les donnes soient dupliquées vers cadastre.data.gouv.fr ou s'il faut modifier le code pour télécharger les données depuis data.gouv.fr.

**Comment by FlorianHergo** [comment]
Bonjour,

Ok merci pour votre info, on va attendre qu'ils répondent 👍

**Comment by benfonty** [comment]
Bonjour,

J'ai [forké le repo](https://github.com/benfonty/DVF-app/tree/feature/generate-mutations-directly-from-data-gouv-fr) afin de pouvoir consulter les données 2020, si vous vous sentez de le builder chez vous.

Ceci dit je vois qu'ils sont en train de s'en occuper de leur côté donc il reste juste à attendre qu'ils le mettent en ligne.

**Comment by ThomasG77** [comment]
Sauf erreur, la question n'est plus d'actualités
